name: Test and build

on: 
  workflow_dispatch:
  

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone du projet dans le runner 
        uses: actions/checkout@v6
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Run Test
        run: npm run test
      
