
name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Send Email
      if: success()
      uses: JaSiLez/smtp-notifier@main
      with:
        server_address: ${{ vars.SMTP_SERVER }}
        server_port: ${{ vars.SMTP_PORT }}
        secure: true
        from: ${{ secrets.FROM_EMAIL }}
        to: digitalcity@yopmail.com
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: "🚀 Deployment fail!"
        html_body: "<h1>Et merde ca à foiré... ! 💩</h1>"
      
